### Get all ntoes
GET http://localhost:3001/api/notes

### Get single note
GET http://localhost:3001/api/notes/6a94e13dc20356f2b60543d9

### Delete single note
DELETE http://localhost:3001/api/notes/6a94dfc89e49842bed047a23
    
### Create new note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "I am slowly getting the hang of backend development",
    "important": true
}

### Unknown endpoint
GET http://localhost:3001/api/help